### PR TITLE
Check against protobuf implicit attrs

### PR DESCRIPTION
**Pull request by seanwarren**
Hello, thanks for this very useful plugin!

This PR makes a small change to allow the plugin to recognise protobuf implicit attrs.

### CODE REVIEW

**Comment by nelfin** [comment]
Haha, fair enough. Thanks @seanwarren!

**Comment by seanwarren** [comment]
Thanks for the quick merge!

**Comment by nelfin** [comment]
Thanks for the PR! I'm preparing a quick release now. Also, cool that you work at Garvan, I'm just around the corner from there at COFA.

**Comment by seanwarren** [comment]
Brilliant, thanks. I actually just finished at the Garvan - I'm working at a different company in London right now. I hear I just missed all the rain....

**Comment by nelfin** [comment]
Yeah, couple of spells, but to be honest it's only felt like winter this last week. Not like midwinter at all.

**Pull request merged**
